#!/bin/bash
# Create minimal valid PNG files for Tauri

cd /Z/Projects/ModelMistress/desktop-app

# Create a base64 encoded minimal 32x32 white PNG
# PNG signature + IHDR + IDAT + IEND - minimal valid file
base64 -d > icons/32x32.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAD0lEQVRYR+3BMQEAAADCoPVPbQ0PoAAAAAAAAACArchKAAAwAECAAAADgABAwAEAAAUBwAAEAgAAAFAAgAAAEMAAABAAQAAgAEAAA
EOF

# Create 128x128 version
base64 -d > icons/128x128.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAGAADAAgCAYAAABzenr0AAAAD0lEQVRYR+3BMQEAAADCoPVPbQ0PoAAAAAAAAACArchKAAAwAECAAAADgABAwAEAAAUBwAAEAgAAAFAAgAAAEMAAABAAQAAgAEAAA
EOF

# Create @2x version
base64 -d > icons/128x128@2x.png << 'EOF'
iVBORw0KGgoAAAANSUhEUgAAAGAADAAgCAYAAABzenr0AAAAD0lEQVRYR+3BMQEAAADCoPVPbQ0PoAAAAAAAAACArchKAAAwAECAAAADgABAwAEAAAUBwAAEAgAAAFAAgAAAEMAAABAAQAAgAEAAA
EOF

echo "Icons created"